# -*- coding: utf-8 -*-
"""E-Commerce Market Intelligence & Strategy Brief - 2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XtdLRtIBYNpzqwI3gx8nNjrTO2d_dmnX
"""

!pip install nest_asyncio

import os
import nest_asyncio
from crewai import Agent, Task, Crew, Process, LLM

# 1. The Magic Fixes
nest_asyncio.apply()
os.environ["GEMINI_API_KEY"] = "Insert your Own"

gemini_llm = LLM(
    model='gemini/gemini-2.5-flash',
    api_key=os.environ["GEMINI_API_KEY"]
)

# ==========================================
print("Waiting for your command...")
target_industry = input("Enter the industry you want the AI team to research: ")
print(f"\nUnderstood! Sending the team to research: {target_industry}\n")
# ==========================================

# 2. HIRE THE 5-STAR AGENT TEAM
researcher = Agent(
    role='Senior Market Researcher',
    goal=f'Gather comprehensive data about the {target_industry} industry trends for 2026.',
    backstory='You are a veteran market researcher who finds hidden data trends.',
    verbose=True,
    llm=gemini_llm
)

strategist = Agent(
    role='Business Strategist',
    goal=f'Analyze the research and identify 3 massive opportunities in {target_industry}.',
    backstory='You spot gaps in the market and turn them into money-making strategies.',
    verbose=True,
    llm=gemini_llm
)

# 🌟 THE FINAL UPGRADE: THE CHIEF RISK OFFICER 🌟
risk_officer = Agent(
    role='Chief Risk Officer',
    goal='Analyze the Strategist\'s proposed opportunities and identify the top 3 critical risks (financial, tech, or market) associated with them.',
    backstory='You are a cynical, brilliant risk analyst. Your job is to protect the company by finding out how plans might fail and suggesting ways to avoid disaster.',
    verbose=True,
    llm=gemini_llm
)

consultant = Agent(
    role='Executive Business Consultant',
    goal=f'Write a highly professional Market Entry Strategy report for {target_industry} that includes both the opportunities and the risk mitigations.',
    backstory='You write clear, stunning executive summaries for top CEOs.',
    verbose=True,
    llm=gemini_llm
)

qa_director = Agent(
    role='Quality Assurance Director',
    goal='Review the report, format it beautifully into Markdown headers, and ensure a SWOT analysis table is included.',
    backstory='You are a strict, perfectionist editor who loves clean Markdown tables, bold headers, and flawless enterprise formatting.',
    verbose=True,
    llm=gemini_llm
)

# 3. GIVE THEM TASKS
task1 = Task(
    description=f'Research the current {target_industry} market and summarize the biggest challenges.',
    expected_output=f'A detailed summary of {target_industry} challenges.',
    agent=researcher
)

task2 = Task(
    description='Take the research and outline 3 clear business solutions/opportunities.',
    expected_output='A bulleted list of 3 strategic business opportunities.',
    agent=strategist
)

task3 = Task(
    description='Review the strategist\'s solutions. Outline 3 major risks and provide a clear mitigation strategy for each to protect the business.',
    expected_output='A critical analysis of 3 risks with corresponding mitigation steps.',
    agent=risk_officer # The new Risk task!
)

task4 = Task(
    description='Combine the opportunities and the risk analysis into a final 4-paragraph executive Business Report.',
    expected_output='A professional business report with clear paragraphs.',
    agent=consultant
)

task5 = Task(
    description='Review the report. Format it with clean headers (#, ##). Build a clear Markdown SWOT Analysis Table. Ensure the final layout looks like an enterprise consultant dashboard.',
    expected_output='A perfectly polished Markdown (.md) document with professional formatting and an embedded data table.',
    agent=qa_director,
    output_file='Enterprise_Strategy_Dashboard.md'
)

# 4. START THE WORK
business_crew = Crew(
    agents=[researcher, strategist, risk_officer, consultant, qa_director],
    tasks=[task1, task2, task3, task4, task5],
    process=Process.sequential,
    max_rpm=10
)

print("Starting the AI Team... Watch them work!\n")
result = await business_crew.kickoff_async()

print(f"\n\n=== FINAL BUSINESS REPORT: {target_industry.upper()} ===")
print("✅ SUCCESS: The AI saved a premium dashboard file named 'Enterprise_Strategy_Dashboard.md'!")
print(result)